config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spaces#index"
  get '/dashboard', to: 'pages#dashboard', as: 'user_dashboard'

  resources :spaces, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create, :update, :show]
  end

  resources :bookings, only: [:update, :destroy, :index] do
    member do
      patch :accept
      patch :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
  validate :start_date_is_in_future
  belongs_to :space
  belongs_to :renter, class_name: "User", foreign_key: :renter_id
  has_one :owner, through: :space

  private

  def start_date_is_in_future
    if start_date < Date.today
      errors.add(:start_date, "must be in the future")
    end
  end
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_default_role, on: :create
  # has_many: bookings
  # has_many
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spaces, dependent: :destroy, foreign_key: :owner_id
  has_many :bookings, dependent: :destroy, foreign_key: :renter_id
  has_one_attached :photo
  validates :role, presence: true, inclusion: { in: %w[owner renter]}

  def owner?
    spaces.exists?
  end

  def renter?
    bookings.exists?
  end

  def set_default_role
    self.role ||= "renter"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end

  def after_sign_in_path_for(resource)
    user_dashboard_path # Redirect to the dashboard after login
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @space = Space.find(params[:space_id])
    @booking = Booking.new
  end

  def create
    @space = Space.find(params[:space_id])
    @booking = Booking.new(booking_params)
    @booking.space = @space
    @booking.renter = current_user
    @booking.status = "pending"
    end_date = booking_params[:start_date].split(" to ").last
    @booking.end_date = end_date


    if @booking.save
      flash[:notice] = "Your booking request has been submitted."
      redirect_to space_path(@space)
    else
      flash[:alert] = "Something went wrong. Please try again."
      redirect_to space_path(@space)
    end
  end

  def index
    if current_user.owner?
      @bookings = Booking.where(space_id: current_user.spaces.pluck(:id))
    else
      @bookings = Booking.where(renter_id: current_user.id)
    end
  end

  def show
  end

  def update
    @booking = Booking.find(params[:id])

    if current_user.owner?
      if params[:status] == 'accepted'
        @booking.update(status: 'accepted')
      elsif params[:status] == 'declined'
        @booking.update(status: 'declined')
      end
    end
    redirect_to user_dashboard_path
  end

  def accept
    @booking = Booking.find(params[:id])
    if current_user.owner?
      @booking.update(status: 'accepted')
      redirect_to user_dashboard_path, notice: 'Booking accepted.'
    else
      redirect_to user_dashboard_path, alert: 'You are not authorized to accept bookings.'
    end
  end

  def decline
    @booking = Booking.find(params[:id])
    if current_user.owner?
      @booking.update(status: 'declined')
      redirect_to user_dashboard_path, notice: 'Booking declined.'
    else
      redirect_to user_dashboard_path, alert: 'You are not authorized to decline bookings.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to user_dashboard_path, alert: "YOU SUCK"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:space_id, :renter_id, :start_date, :end_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def dashboard
    if current_user.owner?
      @spaces = current_user.spaces
      @bookings = Booking.joins(:space).where(spaces: { owner_id: current_user.id })
    elsif current_user.renter?
      @bookings = Booking.where(renter_id: current_user.id)
    end
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @spaces = if current_user&.owner?
                Space.where.not(owner_id: current_user.id)
              else
                Space.all
              end
  end

  def show
    @space = Space.find(params[:id])
    @booking = Booking.new
    @accepted_bookings = @space.bookings.where(status: "accepted")
    @booked_dates = @accepted_bookings.pluck(:start_date, :end_date)
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.owner = current_user
    @space.availability_status = true
    if @space.save
      redirect_to space_path(@space), notice: "Space created successfully!"
    else
      puts @space.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @space = Space.find(params[:id])
    if @space.destroy
      redirect_to user_dashboard_path, alert: "YOU SUCK"
    end
  end


  private

  def space_params
    params.require(:space).permit(:name, :description, :location, :price_per_day, :price_per_hour, :capacity, :availability_status, :photo )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<h1>HELLO!</h1>
<%= render @booking %>

app/views/bookings/index.html.erb
<h1>Bookings Index</h1>
<ul>
<% @bookings.each do |booking| %>
  <li><%= booking.name   %></li>
<% end %>
</ul>

app/views/bookings/new.html.erb
<h1>Request to Book <%= @space.name %></h1>

<%= simple_form_for [@space, @booking] do |t| %>
  <%= t.input :start_date %>
  <%= t.input :end_date, as: :date, label: "End Date" %>
  <%= t.button :submit, class: "btn btn-primary mt-3" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<%= simple_form_for @booking do |t| %>
  <%= t.input :name %>
  <%= t.input :start_date %>
  <%= t.input :end_date %>
  <%= t.input :status %>
  <%= t.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worktree</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body style="background-color:rgb(189, 186, 186);">
    <header class="p-3 text-white mb-3" style="background-color: #393E46">
      <nav class="navbar navbar-expand-lg" style="background-color: #393E46; ">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= image_tag "worktree_logo.png", alt: "logo", height: "50", class: "d-inline-block align-text-top" %>
          </a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav d-flex align-items-center">
              <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link px-3 text-white'%></li>
              <li class="nav-item"><%= link_to 'Dashboard', user_dashboard_path, class: 'nav-link px-3 text-white' %></li>

              <% if current_user %>
                <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link px-3 text-white" %></li>
              <% else %>
                <li class="nav-item"><%= link_to 'Log in', new_user_session_path, class: 'nav-link px-3 text-white' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container mt-3">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show text-center fixed-bottom right-0 m-3"  role="alert">
          <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show text-center fixed-bottom right-0 m-3" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>


    <style>
    .alert {
      animation: fadeOut 5s forwards;
    }

    @keyframes fadeOut {
    0% {
      opacity: 1;
    }
    100% {
      opacity: 0;
      display: none;
    }
    }
    </style>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1 style="font-size: 3rem; font-weight: bold; text-align: center; margin-top: 50px; margin-bottom: 20px;">Dashboard</h1>
<p style="text-align: center; font-size: 1.25rem; color: #555; margin-bottom: 40px;">Welcome, <%= current_user.email %>!</p>


<div class="container">
  <div class="row">
    <% if current_user.owner? %>
      <div class="col-sm-12 col-md-6 col-lg-6"   style="border-right:solid gray;">
        <div class="section-container p-3 mb-4">
          <div style="display: flex; align-items: center; justify-content: space-between; padding: 10px 0;">
            <div style="width: 100px;"></div>
            <h2 class="your-places" style="text-align: center; margin: 0;">Your Places</h2>
            <a href="<%= new_space_path %>" class="add-place" style="background-color: #D65A31; color: #eeeeee; border: none; padding: 8px 12px; cursor: pointer; border-radius: 5px; text-decoration: none;">Add space</a>
          </div>
          <div class="row">
            <% current_user.spaces.each do |space| %>
              <div class="col-md-6 mb-4">
                <div class="card h-100 d-flex flex-column">
                  <%= cl_image_tag space.photo.key, class: "card-img-top" %>

                  <%= button_to space_path(space), method: :delete,  style:"background-color: #222831", data: { confirm: 'Are you sure you want to delete this space?' }, class: "transparent-delete-btn btn-sm position-absolute top-0 end-0 m-2" do %>
                    <i class="fa-solid fa-trash", style="color: #D65A31; background-color: #222831"></i>
                  <% end %>

                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title"><%= space.name %></h5>
                    <p class="card-text"><%= space.location %></p>
                    <a href="<%= space_path(space) %>" class="btn mt-auto"  style="background-color: #D65A31; color: #EEEEEE">View Details</a>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>


      </div>
      <div class="col-sm-12 col-md-6 col-lg-6" style="border-left:solid gray;">
        <div class="section-container p-3 mb-4">
          <div style="justify-content-center">
            <h2 class="text-center" style="height: 60px; margin:0; padding: 10px 0 ">Your Bookings</h2>
          </div>
          <div class="row">
            <% @bookings.each do |booking| %>
              <div class="col-md-6 mb-4">
                <div class="card h-100 d-flex flex-column">
                  <%= cl_image_tag booking.space.photo.key, class: "card-img-top" %>
                  <% if booking.space.owner == current_user %>
                    <%= button_to booking_path(booking), method: :delete, style:"background-color: #222831", data: { confirm: 'Are you sure you want to delete this booking?' }, class: "transparent-delete-btn btn-sm position-absolute top-0 end-0 m-2" do %>
                      <i class="fa-solid fa-trash"  style="color: #D65A31; background-color: #222831"></i>
                    <% end %>
                  <% end %>

                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title"><%= booking.space.name %></h5>
                    <p class="card-text">Request from: <br> <small><%= booking.renter.email%></small></p>
                    <p class="card-text"  style="color: #D65A31;">Status: <%= booking.status %></p>

                    <% if booking.status == 'pending' %>
                      <div class="d-flex justify-content-between">
                        <!-- Accept Booking Button -->
                        <%= button_to accept_booking_path(booking), method: :patch, style:"background-color: #ACD597; border: solid #ACD597", class: "btn btn-success btn-sm" do %>
                          <i class="fas fa-check-circle"></i> Accept
                        <% end %>

                        <!-- Decline Booking Button -->
                        <%= button_to decline_booking_path(booking), method: :patch,style:"background-color: #E73351", class: "btn btn-danger btn-sm" do %>
                          <i class="fas fa-times-circle"></i> Decline
                        <% end %>
                      </div>
                    <% end %>


                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    <% elsif current_user.renter? %>
      <div class="col-md-12">
        <div class="section-container p-3 mb-4">
          <h2 class="text-center">Your Bookings</h2>
          <div class="row">
            <% @bookings.each do |booking| %>
              <div class="col-md-4 mb-4">
                <div class="card h-100 d-flex flex-column">
                  <%= cl_image_tag booking.space.photo.key, class: "card-img-top" %>
                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title"><%= booking.space.name %></h5>
                    <p class="card-text" style="color: #D65A31;"><%= booking.status %></p>
                    <p class="card-text">
                      Dates: <span style="font-size: 0.8em;"><%= booking.start_date.strftime("%d/%m/%Y") %> - <%= booking.end_date.strftime("%d/%m/%Y") %></span>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Welcome to WorkTree</h1>
<p>Find and book the perfect coworking space!</p>

<% if user_signed_in? %>
  <p><%= link_to "Go to Dashboard", user_dashboard_path, class: "btn btn-primary" %></p>
<% else %>
  <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %> or
    <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary" style="background-color: #222831"%></p>
<% end %>

app/views/shared/_flashes.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully signed in to our service.</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-warning alert alert-dismissible fade show" role="alert">
  <span><strong>Mmh</strong> 🤔 seems like you don't have <a href="#">profile picture</a> yet.</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
  <span><strong>Oops!</strong> 😱 a problem has occurred while processing your booking.</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/spaces/_form.html.erb
<%= simple_form_for @space do |f| %>
  <div class="mb-3">
    <%= f.input :name, required: true %>
    <%= f.input :description, required: true %>
    <%= f.input :location, required: true %>
    <%= f.input :price_per_day, required: true %>
    <%= f.input :capacity, required: true %>
  </div>

  <div class="mb-3">
    <%= f.input :photo, as: :file, label: "Upload Space Image" %>
  </div>

  <%= f.submit "Create Space", class: "btn", style:"background-color: #D65A31; color: #EEEEEE"  %>
<% end %>

app/views/spaces/index.html.erb
<div class="container mt-5">
  <h1 class="text-center fw-bold mb-3">Discover Unique Spaces</h1>
  <p class="text-center text-muted mb-4">Find the perfect coworking space for your needs.</p>

  <div class="row">
    <% @spaces.each do |space| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card shadow-lg border-0 rounded-4 overflow-hidden h-100">

          <%= link_to space_path(space), class: "text-decoration-none text-dark" do %>
            <%= cl_image_tag space.photo.key, class: 'card-img-top', height: 220%>

            <div class="card-body d-flex flex-column p-4">
              <h5 class="fw-bold mb-2"><%= space.name %></h5>
              <p class="text-muted"><i class="fas fa-map-marker-alt me-2"></i><%= space.location %></p>

              <div class="d-flex justify-content-between align-items-center mt-2">
                <span class="fw-bold fs-5" style="color: #D65A31;">€<%= space.price_per_day %> / day</span>
                <span class="badge" style= "background-color: #222831"><i class="fa-solid fa-user" style= "background-color: #222831"></i> x <%= space.capacity %></span>
              </div>

              <p class="mt-auto text-muted small">Click to view details</p>
            </div>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/spaces/new.html.erb
<h1>Add a New Space</h1>
<%= render "form" %>
<%= link_to "Back", spaces_path, class: "btn btn-secondary mt-3" %>

app/views/spaces/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      <div class="card shadow-lg border-0 rounded-3">
        <img class="card-img-top"
          src="<%= @space.photo.attached? ? cl_image_path(@space.photo.key) : 'https://a0.muscache.com/im/pictures/miso/Hosting-47118372/original/7cb880ec-a5f7-4131-9174-d4e1b124bb67.jpeg?im_w=1200&im_format=avif' %>"
          alt="<%= @space.name %>"
          style="border-radius: 10px 10px 0 0; width: 100%; height: 250px; object-fit: cover;">
        <div class="card-body p-4">
          <h2 class="card-title fw-bold"><%= @space.name %></h2>
          <p class="text-muted"><%= @space.location %></p>
          <p class="card-text mt-3"><strong>Description:</strong> <%= @space.description %></p>
          <div class="d-flex justify-content-between align-items-center mt-4", style="color: #D65A31" >
            <p class="fw-bold fs-5 ">€<%= @space.price_per_day %> / day</p>
          </div>
          <p class="card-text"><strong>Capacity:</strong> <i class="fa-solid fa-user"></i> x <%= @space.capacity %></p>
          <p class="card-text">
            <strong>Availability:</strong>
            <span class="badge", style="background-color: #D65A31", <%= @space.availability_status ? 'bg-success' : 'bg-danger' %>>
              <%= @space.availability_status ? "Available" : "Not Available" %>
            </span>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <% if current_user&.role == "renter" %>
        <div class="card shadow-sm border-0 rounded-3 p-4">
          <h3 class="fw-bold text-center mb-3">Book this space</h3>
          <%= simple_form_for [@space, @booking] do |f| %>
            <div class="mb-3">
              <%= f.input :start_date, label: "Choose your dates" , as: :string, input_html: { class: "form-control",
                data: { controller: "datepicker", datepicker_dates_value: @booked_dates.to_json } } %>
            </div>
            <div class="mb-3">
              <%= f.input :end_date, as: :hidden %>
            </div>
            <div class="d-grid">
              <%= f.button :submit, "Confirm Booking", class: "btn btn-lg", style:"background-color: #D65A31; color: #EEEEEE"  %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="text-center mt-4">
    <%= link_to "Back to Spaces", spaces_path, class: "btn btn-outline-dark btn-lg" %>
  </div>
</div>